# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
